// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTracking.Db.Models;

public partial class ChangeLog
{
    public int ChangeLogId { get; set; }

    public int TimeEntryId { get; set; }

    public string ChangedByUserId { get; set; }

    public string ChangeType { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual TimeEntry TimeEntry { get; set; }
}