// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTracking.Db.Models;

public partial class TimeEntry
{
    public int TimeEntryId { get; set; }

    public string UserId { get; set; }

    public DateOnly Date { get; set; }

    public decimal? HoursWorked { get; set; }

    public int TypeId { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ChangeLog> ChangeLogs { get; set; } = new List<ChangeLog>();

    public virtual TimeEntryType Type { get; set; }
}