// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTracking.Db.Models;

public partial class TimeEntryType
{
    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public bool IsPaid { get; set; }

    public virtual ICollection<TimeEntry> TimeEntries { get; set; } = new List<TimeEntry>();
}