// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TimeTracking.Db.Models;

public partial class TimeTrackingContext : DbContext
{
    public TimeTrackingContext(DbContextOptions<TimeTrackingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChangeLog> ChangeLogs { get; set; }

    public virtual DbSet<TimeEntry> TimeEntries { get; set; }

    public virtual DbSet<TimeEntryType> TimeEntryTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChangeLog>(entity =>
        {
            entity.HasKey(e => e.ChangeLogId).HasName("PK__ChangeLo__6AD2E8C7175E56E2");

            entity.ToTable("ChangeLog");

            entity.Property(e => e.ChangeType).IsRequired();
            entity.Property(e => e.ChangedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ChangedByUserId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.TimeEntry).WithMany(p => p.ChangeLogs)
                .HasForeignKey(d => d.TimeEntryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChangeLog_TimeEntry");
        });

        modelBuilder.Entity<TimeEntry>(entity =>
        {
            entity.HasKey(e => e.TimeEntryId).HasName("PK__TimeEntr__36FCE7C949AAC1CC");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.HoursWorked).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.Type).WithMany(p => p.TimeEntries)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeEntries_Type");
        });

        modelBuilder.Entity<TimeEntryType>(entity =>
        {
            entity.HasKey(e => e.TypeId);

            entity.Property(e => e.IsPaid).HasDefaultValue(true);
            entity.Property(e => e.TypeName).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}